### PR TITLE
fix: avoid `with_mock()`

### LINKED ISSUE #61: with_mock() is going away
This is a heads up to let you know that `with_mock()` is deprecated and will be made defunct soon. The API functions that made it work are being removed in R 4.5.0, so we'd suggest that you switch to `with_mocked_bindings()` instead.

### LINKED ISSUE #64: with_mock() is going away (2)
This is a second reminder that `with_mock()` is going away in the next release of testthat, which I'm aiming to release October 1. The API functions that made it work are being removed in R 4.5.0, so we'd suggest that you switch to `with_mocked_bindings()/local_mocked_bindings()` instead.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #61
Fixes #64

### CODE REVIEW

File: r/R/shiny.R [hunk 1]
```diff
@@ -177,7 +177,11 @@ parse_mmss <- function(x = "") {
...
 require_shiny <- function(reason) {
-  if (!requireNamespace("shiny", quietly = TRUE)) {
+  if (!has_shiny()) {
     stop(reason, " requires shiny: install.packages('shiny')", call. = FALSE)
   }
 }
+
+has_shiny <- function() {
+  requireNamespace("shiny", quietly = TRUE)
+}
```
Comment (coatless) [inline r/R/shiny.R:187]:
```suggestion
}

```

Comment (gadenbuie) [reply r/R/shiny.R]: Thanks! I'm bringing in `air` in another PR (that I'll push soon)

Comment (coatless) [reply r/R/shiny.R]: Any customization on air? Or: 

```r
usethis::use_air()

usethis::use_github_action(url = "https://github.com/posit-dev/setup-air/blob/main/examples/format-suggest.yaml")
```
